### ISSUE TITLE
Could you provide fully-trained weights?

### ISSUE THREAD

**Issue by Imalne** [haoychen3/CD-Flow#2]
The training process seems to take a long time, is it possible for you to provide the fully trained weights? Thank you very much.

**Comment by mahmoudnafifi** [comment]
I was going to create an issue to ask the same question. @Imalne thanks for initiating this. It would be very helpful to other researchers to use the trained network as a standard metric for color related evaluation.

**Comment by haoychen3** [comment]
Thanks for the reminder. The fully trained weights have been uploaded to Google Drive: https://drive.google.com/file/d/14G4VGvfXAkH86Mr7NaDOYm5fW3-o7TkH/view?usp=sharing.

**Comment by mahmoudnafifi** [comment]
Thanks!

**Comment by Imalne** [comment]
Thanks~
